[tool.poetry]
name = "easyflake"
version = "0.0.1"
description = ""
authors = ["tsuperis <tsuperis@gmail.com>"]
readme = "README.md"
packages = [{include = "easyflake", from = "src"}]

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
toml = "^0.10.2"

[tool.poetry.group.test.dependencies]
freezegun = "^1.2.2"
tox = "^4.4.5"

[tool.poetry.group.lint.dependencies]
flake8 = "^5.0.4"
mypy = "^1.0.1"
isort = "^5.12.0"
black = "^23.1.0"

[tool.isort]
profile = "black"

[tool.mypy]
ignore_missing_imports = true

[build-system]
requires = ["poetry-core>=1.2"]
build-backend = "poetry.core.masonry.api"
